apiVersion: v1
kind: Service
metadata:
  name: my-jhttp-svc
  labels:
    app: jhttp
spec:
  type: LoadBalancer
  ports:
  - port: 8888
  selector:
    app: jhttp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jhttp
  labels:
    app: jhttp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jhttp
  template:
    metadata:
      labels:
        app: jhttp
    spec:
      containers:
      - name: jhttp
        image: {{.Values.image}}
        ports:
        - containerPort: 8888
